spring:
  application:
    name: springCloud-Gateway-Exam
logging:
  level:
    org.springframework.cloud.gateway: TRACE
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001